title: My Blog
author: William Anil
email: wanil@ebnet.org
description: > # this means to ignore newlines until "baseurl:"
  Welcome to my new website, I am a tenth grader who goes to East Brunwcik High school. Here you can find my social media accounts and my "brag sheet".

# social links
Snapchat: b4obama
Instagram: w_i_l_l_0_3_3

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
